server:
  port: 8888

mybatis-plus:
  global-config:
    field-strategy: NOT_NULL
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    default:
      driverClassName: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&serverTimezone=GMT%2B8&useUnicode=true&autoReconnect=true
      username: "root"
      password: "root"
